config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#top'
  get 'about' => 'products#about', as: 'products_about'
  post 'products/guest_sign_in', to: 'products#new_guest'
  patch "users/usubscribe" => "users#usubscribe", as: 'users_usubscribe'
  get "users/withdraw" => "users#withdraw", as: 'users_withdraw'
  resources :products do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy, :show]
    get "index_favorites" => "favorites#index"
  end
  resources :users do
    get :followings, on: :member
  end

  resources :relationships, only: [:create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  # resources :genres, only: [:index, :create, :edit, :update]
  get "search" => "users#search"
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_product, only: %i[create destroy]
  def create
  	@product = Product.find(params[:product_id])
    favorite = current_user.favorites.new(product_id: @product.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
  	@product = Product.find(params[:product_id])
    favorite = current_user.favorites.find_by(product_id: @product.id)
    favorite.destroy
    # redirect_to request.referer
  end

  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
  end

  def show
    @product = Product.find(params[:product_id])
    @favorites = Favorite.where(product_id: @product.id).all
  end

  private

  # def set_product
  #   @product = Product.find(params[:product_id])
  # end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if product.favorited_by?(current_user) %>
  <%= link_to product_favorites_path(product), method: :delete, remote: true do %>
    <span class="glyphicon glyphicon-heart"><%= product.favorites.count%></span>
  <% end %>
<% else %>
  <%= link_to product_favorites_path(product), method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart-empty"><%= product.favorites.count %></span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @product.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {product: @product}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @product.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {product: @product}) %>");

app/views/favorites/index.html.erb
<h2 class="text-center">お気に入り一覧</h2>

<% @favorites.each do |favorite| %>
	<% product = Product.find(favorite.product_id) %>
	<ul class="list-group">
		<li class="list-group-item text-center"><%= link_to product.name, product_path(product) %>
			<span class="ml-5">
				<%#= link_to "削除", product_favorites_path(product), method: :delete, remote: true, id: :"js-favorite-button-for-product-#{product.id}" %>
			</span>
		</li>
	</ul>
<% end %>
<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>

app/views/favorites/show.html.erb
<h2 class="text-center">お気に入り登録ユーザー一覧(<%= @favorites.length %>人)</h2>

<% @favorites.each do |favorite| %>
	<% @user_id = favorite.user_id %>
	<% user = User.find(@user_id) %>
	<li class="list-group-item text-center"><%= link_to user.name, user_path(user) %></li><br>
<% end %>
<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>