config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#top'
  get 'about' => 'products#about', as: 'products_about'
  post 'products/guest_sign_in', to: 'products#new_guest'
  patch "users/usubscribe" => "users#usubscribe", as: 'users_usubscribe'
  get "users/withdraw" => "users#withdraw", as: 'users_withdraw'
  resources :products do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy, :show]
    get "index_favorites" => "favorites#index"
  end
  resources :users do
    get :followings, on: :member
  end

  resources :relationships, only: [:create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  # resources :genres, only: [:index, :create, :edit, :update]
  get "search" => "users#search"
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  #フォロー中間テーブルを設定し、フォローしているuserたちを取得
  has_many :followings, through: :relationships, source: :follow
  #上記の逆、入り口をfollow_idとする
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  #user_idを入り口
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  enum prefecture_code: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  validates :name, presence: true, length: { in: 1..20 }, uniqueness: true
  validates :email, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end


  def User.search(search, user_or_product)
    if user_or_product == "1"
       User.where(['name LIKE ?', "%#{search}%"])
    else
       User.all
    end
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def index
    @users = User.page(params[:page]).reverse_order.per(6)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
    @relationship = current_user.relationships.find_by(follow_id: @user.id)  
    @set_relationship = current_user.relationships.new
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def withdraw
  end

  def usubscribe
      @user = User.find(current_user.id)
      if @user.update!(is_deleted: true)
         sign_out current_user
      end
      redirect_to root_path
  end

  def search
    @user_or_product = params[:option]
    if @user_or_product == "1"
       @users = User.search(params[:search], @user_or_product)
    elsif @user_or_product == "2"
       @products = Product.search(params[:search], @user_or_product)
    else
      @prefecture_code = Product.search(params[:search], @user_or_product)
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :prefecture_code, :email, :biography, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="text-center">登録情報編集</h2>

<%= form_for(@user) do |f| %>
<% if current_user.id == 3 %>
<h1 class="text-center">ゲストユーザーの編集はご遠慮ください。</h1>
<% else %>
  <div class="container">
   <div class="row">
      <div class="col-xs-3 col-xs-offset-3"><%= f.label :名前 %></div>
      <div class="col-xs-6"><%= f.text_field :name %></div>
   </div><br>

    <div class="row">
      <div class="col-xs-3 col-xs-offset-3"><%= f.label :メールアドレス %></div>
      <div class="col-xs-6"><%= f.text_field :email %></div>
    </div><br>

    <div class="row">
      <div class="col-xs-3 col-xs-offset-3"><%= f.label :自己紹介 %></div>
      <div class="col-xs-6"><%= f.text_area :biography %></div>
    </div><br>

    <div class="row">
      <div class="col-xs-3 col-xs-offset-3"><%= f.label :都道府県 %></div>
      <div class="col-xs-6"><%= f.select :prefecture_code, User.prefecture_codes.keys, {} %></div>
    </div><br>

    <div class="actions col-xs-5 col-xs-offset-7">
      <%= f.submit "変更を保存する", class: "btn-gradient-2d-simple mb-2" %>
    </div>
<% end %>
<% end %> 
  </div>

app/views/users/followings.html.erb
<h2 class="text-center">フォローしている人</h2>

<% @users.each do |user| %>
	<li class="list-group-item text-center">
		<%= link_to user.name, user_path(user.id) %>さん
	</li>
<% end %>
<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>

app/views/users/index.html.erb
<h3 class="text-center">会員一覧</h3>
	<table class="table customers-index">
		<thead class="thead-light">
			<th class="text-center">氏名</th>
			<th>在住</th>
		</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td class="text-center"><%= link_to user.name, user_path(user) , length: 10 %></td>
			<td><%= user.prefecture_code %></td>
		<% end %>
		</tr>
	</tbody>
	</table>

<%= paginate @users %>

app/views/users/search.html.erb
<% if @user_or_product == "1"%>
    <h1 class="text-center">ユーザー</h1>
    <% @users.each do |user| %>
        <li class="list-group-item text-center"><%= link_to user.name, user_path(user) %></li>
    <% end %>
<% elsif @user_or_product == "2" %>
    <h2 class="text-center">場所</h2>
    <% @products.each do |product| %>
        <li class="list-group-item text-center"><%= link_to product.name, product_path(product.id) %></li>
    <% end %>

<!-- 現在使用不可　たぶん使えないので別の検索歩法を考える　ちなみにenumの数字でなら検索できる　データ型を変えないとたぶん無理 -->
<% elsif @user_or_product == "3" %>
    <h2 class="text-center">都道府県別場所</h2>
    <% @prefecture_code.each do |product| %>
        <%= product.name %>
        <li class="list-group-item text-center"><%= product.prefecture_code %></li>
    <% end %>
<% else %>
<% end %>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>
	<h2 class="text-center">マイページ</h2>
<% else %>
	<h2 class="text-center"><%= @user.name %>&nbsp;ページ</h2>
<% end %>

<table class="table table-hover">
	<tr class="brown-border">
		<td class="active text-center">名前</td>
		<td><%= @user.name %></td>
	</tr>

	<tr class="brown-border">
		<td class="active text-center">自己紹介</td>
		<td><%= @user.biography %></td>
	</tr>

	<tr class="brown-border">
		<td class="active text-center">在住</td>
		<td><%= @user.prefecture_code %></td>
	</tr>

	<tr class="brown-border">
		<td class="active text-center">お気に入り一覧</td>
		<td><%= link_to "お気に入り一覧", product_index_favorites_path(@user) %></td>
	</tr>

	<tr class="brown-border">
		<td class="active text-center">フォロー一覧</td>
		<td><%= link_to "フォロー: #{@user.followings.count}", followings_user_path(@user.id) %></td>
	</tr>
	
	<% unless @user.id == current_user.id %>
		<tr class="brown-border">
			<td class="active text-center">フォロー</td>
			<td>
  		<!-- フォロー機能 -->
				<%= render 'relationships/follow_button' %>
			</td>
		</tr>

	<tr class="brown-border">
		<td class="active text-center">チャット</td>
		<td>
			<% if @user.id == current_user.id %>

			<% else %>
  				<% if @isRoom == true %>
    				<p class="btn-gradient-1d-simple"><a href="/rooms/<%= @roomId %>"><font color="#fff">チャットへ</font></a>
  				<% else %>
    				<%= form_for @room do |f| %>
      					<%= fields_for @entry do |e| %>
        					<%= e.hidden_field :user_id, :value=> @user.id %>
      					<% end %>
      					<%= f.submit "チャットを始める", class: "btn-gradient-1d-simple" %>
    				<% end %>
  				<% end %>
			<% end %>
		</td>
	</tr>
	<% end %>
</table>

<div class="row">
	<table align="right">
		<tbody>
			<tr><% if @user.id == current_user.id %>
					<% if current_user.id == 3 %>
					<% else %>
						<td><%= link_to  "編集する", edit_user_path(@user), class: "btn-gradient-3d-simple" %></td>
						<td><%= link_to "パスワードを変更する", edit_user_registration_path, class: "btn-gradient-1d-simple" %></td>
						<td><%= link_to "退会する", users_withdraw_path, class: "btn-gradient-4d-simple" %></td>
					<% end %>
				<% end %>
			</tr>
		</tbody>
	</table>
</div>

app/views/users/withdraw.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center mb-2">
      <h2 class="title">本当に退会しますか？</h2>
      <p>退会すると、会員登録情報や<br>
      場所が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。<br>
      </p>
      <% if current_user.id == 3 %>
      <% else %>
      <%= link_to "退会しない",user_path(current_user.id), class: "btn01" %>
      <%= link_to "退会する", users_usubscribe_path, method: :patch, "data-confirm" => "本当に退会するの？", class: "btn02" %>
      <% end %>
    </div>
  </div>
</div>