config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#top'
  get 'about' => 'products#about', as: 'products_about'
  post 'products/guest_sign_in', to: 'products#new_guest'
  patch "users/usubscribe" => "users#usubscribe", as: 'users_usubscribe'
  get "users/withdraw" => "users#withdraw", as: 'users_withdraw'
  resources :products do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy, :show]
    get "index_favorites" => "favorites#index"
  end
  resources :users do
    get :followings, on: :member
  end

  resources :relationships, only: [:create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  # resources :genres, only: [:index, :create, :edit, :update]
  get "search" => "users#search"
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :image
	belongs_to :user, optional: true
	has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  enum prefecture_code: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  validates :name, presence: true, length: { in: 1..20 }, uniqueness: true
  validates :introduction, presence: true, length: { in: 1..80 }, uniqueness: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  def Product.search(search, user_or_product)
    if user_or_product == "2"
     Product.where(['name LIKE ?', "%#{search}%"])
    elsif user_or_product == "3"
     Product.where(['prefecture_code LIKE ?', "%#{search}%"])
    else
     Product.all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :only => [:show, :index, :new, :create, :edit, :update]
  # before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def index
    @products = Product.page(params[:page]).reverse_order.per(5).includes([:reviews])
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def about
  end

  def top
    @recommendation = Product.where(status: "true" ).limit(8).order(created_at: :desc)

  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    if product.save
      flash[:notice] = "場所を登録しました。"
      redirect_to product_path(product)
    else
      flash[:notice] = "登録できませんでした。"
      render :new
   end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
       flash[:notice] = "場所を更新しました。"
       redirect_to product_path(product.id)
    else
      flash[:notice] = "更新できませんでした。"
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end

  def new_guest
    user = User.find_or_create_by!(email: 'gguuest@example.com', name: 'ゲストアカウント') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。よろしくお願いします！'
  end

  private

  def product_params
    params.require(:product).permit(:name, :introduction, :image, :status, :genre_id, :genre_name, :prefecture_code, :city, :street)
  end

  def ensure_correct_user
    @product = Product.find(params[:id])
    unless @product.user == current_user
      redirect_to products_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/about.html.erb
<div class="f-container">
	<div class="image4">
		<p class="pimage4 text-center pt-5">
			たまには、いつもと違う調べ方しませんか？
		</p>
	</div>
</div>

<div class="container">
	<div class="row about_row">
		<div class="col-xs-6 text-center">
			<h5 class="bold">たまには、いつもと違う休息しませんか？</h5>
		</div>
		<div class="col-xs-6 image1">
		</div>
	</div>

	<div class="row about_row">
			<div class="col-xs-6 image2">
  			</div>
		<div class="col-xs-6 text-center">
			 <h5 class="bold">たまには、いつもと違う移動方法使いませんか？</h5>
		</div>
	</div>

	<div class="row about_row">
		<div class="col-xs-6 text-center">
			 <h5 class="bold">たまには、いつもと違う時間に出掛けませんか？</h5>
		</div>
		<div class="col-xs-6 image3">
  		</div>
	</div>
</div>

app/views/products/edit.html.erb
<% @product = Product.new unless @product %>

<div class="container">
	<div class="row">
		<h1>編集画面</h1>
		<%= form_for(@product) do |f| %>
			<div class="col-xs-6">
				<h4>画像</h4>
					<%= attachment_image_tag @product, :image, format: 'jpeg', fallback: "no_data.jpg", size: "300x300" %><br><br>
					<%= f.attachment_field :image %>
			</div>

			<script>
				$(function(){
    			// inputのidから情報の取得
    			$('#product_image').on('change', function (e) {
				// ここから既存の画像のurlの取得
    			var reader = new FileReader();
    			reader.onload = function (e) {
        		$(".image").attr('src', e.target.result);
    			}
				// ここまで
    			reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
				});
				});
			</script>

			<div class="col-xs-6">
				<h4>場所名</h4>
				<%= f.text_field :name %>
				<h4>場所説明</h4>
				<%= f.text_area :introduction %>
				<h4>都道府県</h4>
				<%= f.select :prefecture_code, User.prefecture_codes.keys, {} %>
				<button type="button" class="btn btn-default" data-toggle="popover" data-animation="true" title="都道府県を選択" data-content="わからなければ---のままでお願いします。">
         			<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
      			 </button>
				<h4>市町村</h4>
				<%= f.text_field :city %>
				<button type="button" class="btn btn-default" data-toggle="popover" data-animation="true" title="市町村、番地" data-content="わからない場合は空白でお願いします。">
         			<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
       			</button>
				<h4>番地</h4>
				<%= f.text_field :street %>
				<h4>現在の状況</h4>
				<%= f.select :status, {"現在もあります" => "true", "現在はありません" => "false"} %><br><br>
				<div class="button">
					<%= f.submit "変更を保存", class:"btn-gradient-2d-simple" %>
				</div>
		<% end %> 
			</div>
	</div>
</div>
<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1>場所一覧</h1>
			<%= link_to new_product_path do %>
          		<i class="glyphicon glyphicon-plus-sign icon" style = "font-size: 20px">場所登録</i>
        	<% end %>

			<% @products.each do |product| %>
				<div class="row">
					<div class="col-xs-4">
						<%= attachment_image_tag product, :image, :fill, 200, 200, size: "200x200", format: 'jpeg', fallback: "no_data.jpg" %><br><br>
					</div>
					<div class="col-xs-4">
						<h3><%= link_to product.name, product_path(product.id) %></h3>
						<div id="favorites_buttons_<%= product.id %>">
							<%= render partial: 'favorites/favorite', locals: { product: product} %>
          				</div>
          				<div>
          					<%= product.prefecture_code %>
          				</div>
					</div>

					<div class="col-xs-4">
						<div class="content average-score">
							<div class="star-rating">
								<div class="star-rating-front" style="width: <%= product.review_score_percentage %>%">★★★★★</div>
								<div class="star-rating-back">★★★★★</div>
							</div>
							<div class="average-score-display">
								<%= product.avg_score %>点 (<%= product.reviews.count %>件のレビュー)
							</div>
						</div>

						<%= link_to product_reviews_path(product) do %>
							レビューを見る
						<% end %>

						<%= link_to product_path(product) do %>
							レビューを書く
						<% end %>
					</div><br>
				</div>
			<% end %>
		</div>
	</div>
</div>
<%= paginate @products %>

app/views/products/new.html.erb
<% @product = Product.new unless @product %>
<div class="container">
    <div class="row">
        <h1>新規登録</h1>
        <%= form_for(@product) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
            <div class="col-xs-6">
                <h4>画像</h4>
                    <%= attachment_image_tag @product, :image, format: 'jpeg', fallback: "no_data.jpg", size: "300x300" %><br><br>
                    <%= f.attachment_field :image %>
            </div>

            <script>
                $(function(){
                // inputのidから情報の取得
                $('#product_image').on('change', function (e) {
                // ここから既存の画像のurlの取得
                var reader = new FileReader();
                reader.onload = function (e) {
                $(".image").attr('src', e.target.result);
                }
                // ここまで
                reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
                });
                });
            </script>

            <div class="col-xs-6">
                <h4>場所名</h4>
                <%= f.text_field :name, :placeholder => "1~20文字" %>
                <h4>場所説明</h4>
                <%= f.text_area :introduction, :placeholder => "1~80文字" %>
                <h4>都道府県</h4>
                <%= f.select :prefecture_code, User.prefecture_codes.keys, {} %>
                <button type="button" class="btn btn-default" data-toggle="popover" data-animation="true" title="都道府県を選択" data-content="わからなければ---のままでお願いします。">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                 </button>
                <h4>市町村</h4>
                <%= f.text_field :city %>
                <button type="button" class="btn btn-default" data-toggle="popover" data-animation="true" title="市町村、番地" data-content="わからない場合は空白でお願いします。">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                </button>
                <h4>番地</h4>
                <%= f.text_field :street %>
                <h4>現在の状況</h4>
                <%= f.select :status, {"現在もあります" => "true", "現在はありません" => "false"} %><br><br>
                <%= f.submit "新規登録", class:"btn-gradient-2d-simple" %>
        <% end %>
            </div>
    </div>
</div>
<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>

app/views/products/show.html.erb
<div class="containre">
	<div class="row">
		<div class="col-xs-12">
			<h2>詳細</h2>
			<div class="col-xs-6">
				<h4>画像</h4>
				<%= attachment_image_tag @product, :image, :fill, 500, 500, size: "300x300", format: 'jpeg', fallback: "no_data.jpg" %>
			</div>
			<div class="col-xs-3">
				<h4>場所の名前</h4>
				<%= @product.name %>
				<!-- お気に入り -->
				<td>
            		<div id="favorites_buttons_<%= @product.id %>">
						<%= render partial: 'favorites/favorite', locals: { product: @product} %>
          			</div>
          		</td>
				<h3>場所の説明</h3>
				<%= @product.introduction %>
				<h3>登録日</h3>
				<%= @product.created_at.strftime('%Y/%m/%d') %>
				<h3>住所</h3>
				<%= @product.prefecture_code %>
				<%= @product.city %>
				<%= @product.street %>
				<h3>現在の状況</h3>
				<% if @product.status? %>
					現在もあります
				<% else %>
					現在はもうありません
				<% end %><br><br>
				<p>
					<%= link_to "場所編集", edit_product_path(@product), class:"btn-gradient-3d-simple" %>
					<%= link_to "場所削除", product_path(@product), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn-gradient-1d-simple" %>
				</p>
			</div>
			<!-- 星レビュー -->
			<div class="card-content">
				<div class="content average-score">
					<div class="star-rating">
						<div class="star-rating-front" style="width: <%= @product.review_score_percentage %>%">★★★★★</div>
						<div class="star-rating-back">★★★★★</div>
					</div>
					<div class="average-score-display">
						<%= link_to product_reviews_path(@product) do %>
						<%= @product.avg_score %>点 (<%= @product.reviews.count %>件のレビュー)
						<% end %>
					</div>
				</div>
			</div><br>

			<%= render 'reviews/form', review: @review, product: @product %>
			<%= link_to "お気に入りした人", product_favorites_path(@product), class:"btn btn-info" %>
		</div>
	</div>
</div>

<%= link_to :back do %>
  <button class="btn02">戻る</button>
<% end %>

app/views/products/top.html.erb
<style>
.kotei {position: -webkit-sticky;position: sticky;top: 0;}
</style>
<!-- ビデオ -->
<div class="wrap-video">
  <div class="text">
    <p class="headline"><b><ruby>DOKOIKUNYA<rt>どこ行くんや</rt></ruby></b></p>
  </div>
  <video src="videos/video.mp4" muted autoplay loop></video>
</div>

<div class="container">
    <% if user_signed_in? %>
    <div class="row">
        <h3 class="New">SPOT</h3>
        <div class="col-xs-12">
            <% @recommendation.each do |product| %>
            <div class="col-xs-3">
                <%= link_to product_path(product) do %>
                    <%= attachment_image_tag product, :image, :fill, 200, 200, fallback: "no_data.jpg", size:"200x200", class: "img-rounded" %>
                    <p><%= product.name.truncate(12, omission: '...') %></p>
                    <p><%= product.prefecture_code %></p>
                <% end %>
            </div>
            <% end %>
            <p class="pull-right btn btn02"><%= link_to "Read more▶️", products_path %></p>
        </div>
    </div>
    <% end %>
</div>
 


<!-- スタート -->
<% if user_signed_in? %>
<% else %>
<div class="btn-engine-start">
<%= link_to products_guest_sign_in_path, method: :post ,class:"btn btn-engine-start-in" do %>
START<br>ゲスト<br><span>ログイン</span>
<% end %>
</div>
<% end %>