config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#top'
  get 'about' => 'products#about', as: 'products_about'
  post 'products/guest_sign_in', to: 'products#new_guest'
  patch "users/usubscribe" => "users#usubscribe", as: 'users_usubscribe'
  get "users/withdraw" => "users#withdraw", as: 'users_withdraw'
  resources :products do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy, :show]
    get "index_favorites" => "favorites#index"
  end
  resources :users do
    get :followings, on: :member
  end

  resources :relationships, only: [:create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  # resources :genres, only: [:index, :create, :edit, :update]
  get "search" => "users#search"
  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message
  
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :image
	belongs_to :user, optional: true
	has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  enum prefecture_code: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  validates :name, presence: true, length: { in: 1..20 }, uniqueness: true
  validates :introduction, presence: true, length: { in: 1..80 }, uniqueness: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  def Product.search(search, user_or_product)
    if user_or_product == "2"
     Product.where(['name LIKE ?', "%#{search}%"])
    elsif user_or_product == "3"
     Product.where(['prefecture_code LIKE ?', "%#{search}%"])
    else
     Product.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :score, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  #フォロー中間テーブルを設定し、フォローしているuserたちを取得
  has_many :followings, through: :relationships, source: :follow
  #上記の逆、入り口をfollow_idとする
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  #user_idを入り口
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  enum prefecture_code: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  validates :name, presence: true, length: { in: 1..20 }, uniqueness: true
  validates :email, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end


  def User.search(search, user_or_product)
    if user_or_product == "1"
       User.where(['name LIKE ?', "%#{search}%"])
    else
       User.all
    end
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.includes([:user])
      @message = Message.new
      @entries = @room.entries.includes([:user])
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def index
    @users = User.page(params[:page]).reverse_order.per(6)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
    @relationship = current_user.relationships.find_by(follow_id: @user.id)  
    @set_relationship = current_user.relationships.new
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def withdraw
  end

  def usubscribe
      @user = User.find(current_user.id)
      if @user.update!(is_deleted: true)
         sign_out current_user
      end
      redirect_to root_path
  end

  def search
    @user_or_product = params[:option]
    if @user_or_product == "1"
       @users = User.search(params[:search], @user_or_product)
    elsif @user_or_product == "2"
       @products = Product.search(params[:search], @user_or_product)
    else
      @prefecture_code = Product.search(params[:search], @user_or_product)
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :prefecture_code, :email, :biography, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
	<div class="container">
	  <div class = "row" style="margin-bottom: 30px">
		  <div class = "error">
		        <ul>
		            <% model.errors.full_messages.each do |message| %>
		               <li><%= message %></li>
		            <% end %>
		        </ul>
		    </div>
	  </div>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-3">
	<div class="container mt-2">
		<div class="row">
			<div class="col-10 text-center gundam">
				© 2020 White GUNDUM.
				<button type="button" class="btn-xs" data-toggle="modal" data-target="#sampleModal">
				<i class="fas fa-robot robot"></i>
				</button>
			</div>
		</div>
			<div class="pull-right pb-1">
				<!--以下twitter-->
				<a href="#" class="btn-social-circle btn-social-circle--twitter">
  					<i class="fa fa-twitter"></i>
				</a>

				<!--以下facebook-->
				<a href="#" class="btn-social-circle btn-social-circle--facebook">
			  		<i class="fa fa-facebook"></i>
				</a>

				<!--以下pocket-->
				<a href="#" class="btn-social-circle btn-social-circle--pocket">
				 	<i class="fa fa-get-pocket"></i>
				</a>

				<!--以下feedly-->
				<a href="#" class="btn-social-circle btn-social-circle--feedly">
 					<i class="fa fa-rss"></i>
				</a>
			</div>
	</div>
</footer>



<!-- モーダル・ダイアログ -->
<div class="modal fade" id="sampleModal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span>×</span></button>
				<h4 class="modal-title">White GUNDUM. 説明</h4>
			</div>
			<div class="modal-body">
				DOKOIKUNYA作成者が初めて組んだ、チーム開発のチーム名です。
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar-inverse navbar-expand-lg navbar-light fixed-top kotei" id="mainNav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DOKOIKUNYA", root_path, class:"navbar-brand" %>
    </div>
    
    <div class="collapse navbar-collapse" id="navbarEexample7">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "ABOUT", products_about_path %></li>
          <li class="nav-item"><%= link_to "SPOT", products_path %></li>
          <li class="nav-item"><%= link_to "MY PAGE", user_path(current_user.id) %></li>
          <li class="nav-item"><%= link_to "MEMBER", users_path %></li>
          <li class="nav-item"><%= link_to "CONTACT", inquiry_path %></li>
          <li class="nav-item"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
          <li class="nav-item navbar-text">ようこそ♪ <%= current_user.name %> さん</li>
      </ul>
          <p class="nav-item navbar-right">
            <button type="button" class="btn mt-1" data-toggle="modal" data-target="#searchModal">
              <i class="fab fa-sistrix"></i>
            </button>
          </p>

        <% else %>
          <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to "ABOUT", products_about_path %></li>
            <li class="nav-item"><%= link_to "SIGNUP", new_user_registration_path %></li>
            <li class="nav-item"><%= link_to "LOGIN", new_user_session_path %></li>
            <li class="nav-item"><%= link_to "CONTACT", inquiry_path %></li>
            <li class="nav-item"><%= link_to 'ゲストログイン（閲覧用）', products_guest_sign_in_path, method: :post ,class:"fas fa-sign-in-alt" %></li>
        <% end %>
          </ul>
    </div>
  </div>
</nav>

<!-- モーダル、サーチ -->
<div class="modal fade" id="searchModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h4 class="modal-title">検索</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(search_path, :method => 'get') do %>
          <div class="form-group navbar-form navbar-left">
            <%= select_tag(:option, options_for_select([["ユーザー名検索", "1"],["場所名検索", "2"]])) %>
            <!-- ,["都道府県別検索", "3"] -->
            <%= text_field_tag :search %>
            <%= submit_tag 'Search', class:"btn01" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn02" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>DOKOIKUNYA</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body id="page-top">
      <!-- ヘッター -->
      <%= render 'layouts/header' %>

      <!-- エラー -->
      <% if flash[:notice] %>
        <div class="notification is-info">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <%= yield %>

      <!-- フッター -->
      <%= render 'layouts/footer' %>

  </body>
</html>